[package]
name = "test_serial"
version = "0.1.0"
authors = ["Leoni Mota Loris <leoniloris1@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
serialport = "3.3.0"
